export default defineAppConfig({
  ui: {
    colors: {
      primary: 'red',
      neutral: 'zinc',
    },
    icons: {
      close: 'i-material-symbols-close-rounded',
      check: 'i-material-symbols-check-rounded',
      chevronDown: 'i-material-symbols-keyboard-arrow-down-rounded',
      chevronUp: 'i-material-symbols-keyboard-arrow-up-rounded',
      chevronLeft: 'i-material-symbols-chevron-left-rounded',
      chevronRight: 'i-material-symbols-chevron-right-rounded',
      loading: 'i-material-symbols-progress-activity',
      search: 'i-material-symbols-search-rounded',
      info: 'i-material-symbols-info-outline-rounded',
      warning: 'i-material-symbols-warning-outline-rounded',
      error: 'i-material-symbols-error-outline-rounded',
      success: 'i-material-symbols-check-circle-outline-rounded',
      external: 'i-material-symbols-open-in-new-rounded',
      minus: 'i-material-symbols-remove-rounded',
      plus: 'i-material-symbols-add-rounded',
      dark: 'i-material-symbols-dark-mode-outline-rounded',
      light: 'i-material-symbols-light-mode-outline-rounded',
      system: 'i-material-symbols-computer-outline-rounded',
      ellipsis: 'i-material-symbols-more-horiz',
      menu: 'i-material-symbols-menu-rounded',
      copy: 'i-material-symbols-content-copy-outline-rounded',
      copyCheck: 'i-material-symbols-inventory-rounded',
      eye: 'i-material-symbols-visibility-outline-rounded',
      eyeOff: 'i-material-symbols-visibility-off-outline-rounded',
      arrowLeft: 'i-material-symbols-arrow-back-rounded',
      arrowRight: 'i-material-symbols-arrow-forward-rounded',
      arrowUp: 'i-material-symbols-arrow-upward-rounded',
      arrowDown: 'i-material-symbols-arrow-downward-rounded',
    },
  },
});
