name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pxls-webclient:workflowbuild
    - name: Tag the docker with time
      run: docker tag pxls-webclient:workflowbuild runem46/pxls-webclient:$(date +%s)
    - name: Tag the docker image with latest
      run: docker tag pxls-webclient:workflowbuild runem46/pxls-webclient:latest
